spring:
  datasource:
    username: root
    password: Li@3188057.
    url: jdbc:mysql://43.143.58.38:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver   #驱动
  cloud:
    nacos:
      discovery:
        server-addr: 43.143.58.38:8848
#        namespace: 50eb030d-db7b-48fb-920a-2f45bb4bc938
  #    alibaba:
#      seata:
#        tx-service-group: ${spring.application.name}-tx-group
  application:
    name: gulimall-order
  thymeleaf:
    cache: false
  redis:
    password: Li@3188057.
    host: 43.143.58.38
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  #设置主键自增

server:
  port: 7100


#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  # 事务群组（可以每个应用独立取名，也可以使用相同的名字），要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
#  tx-service-group: ${spring.application.name}-tx-group
#  config:
#    type: nacos
#    # 需要和server在同一个注册中心下
#    nacos:
#      serverAddr: 127.0.0.1:8848
#      # 需要server端(registry和config)、nacos配置client端(registry和config)保持一致
#      group: SEATA_GROUP
#      username: "nacos"
#      password: "nacos"
#      namespace: 50eb030d-db7b-48fb-920a-2f45bb4bc938
#  registry:
#    type: nacos
#    nacos:
#      # 需要和server端保持一致，即server在nacos中的名称，默认为seata-server
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      username: "nacos"
#      password: "nacos"
#      namespace: 50eb030d-db7b-48fb-920a-2f45bb4bc938


# feign组件超时设置，用于查看seata数据库中的临时数据内容
feign:
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000




